### PR TITLE
add option to restrict chapter range

### PR DESCRIPTION
**Pull request by benneti**
A slighlty more general approach to solve https://github.com/hurlenko/mloader/issues/12 .
This makes it possible to only download chapters within begin <= chapter <= end.

### CODE REVIEW

**Comment by Nickelza** [comment]
> A slighlty more general approach to solve #12 .
> This makes it possible to only download chapters within begin <= chapter <= end.
Hello. I tried changing the files with you version but keep running into the following error:

```
13.07.2021 17:29:02 |   INFO   |  __main__.py   177  | Started export
13.07.2021 17:29:02 |  ERROR   |  __main__.py   183  | Failed to download manga
Traceback (most recent call last):
  File "__main__.py", line 181, in main
    loader.download(title_ids=titles, chapter_ids=chapters, dst=out_dir, begin=begin, end=end)
TypeError: download() got an unexpected keyword argument 'begin'
```

I suppose the module will have to be recompiled in some way. I've tried with `python -m compileall` at no avail. Any suggestions?

**Comment by benneti** [comment]
how did you install it?
It seems to me that you did not replace all files you need to replace, i.e. I think you did not replace loader.py.

**Comment by Nickelza** [comment]
Changed both files, __main__ and loader. Seems like main still somehow refers to a previous version of loader, which is quite odd.
Unfortunately I'm not quite versed with Python, and what I found online pointed to recompiling the module which isn't working for me

**Comment by benneti** [comment]
How did you install it?
You could try the following (assuming python=python3 and is new enough to include venv):
``` bash
mkdir venv
python -m venv venv
./venv/bin/pip install -U pip
./venv/bin/pip install -U mloader gallery-dl
```
and then replace __main__.py and loader.py in all venv/lib??/python??/site-packages/mloader/ where ?? means go through all the possibilities, then you can user mloader in venv/bin which just wraps mloader in the venv

**Comment by Nickelza** [comment]
> How did you install it?
> You could try the following (assuming python=python3 and is new enough to include venv):
> 
> ```shell
> mkdir venv
> python -m venv venv
> ./venv/bin/pip install -U pip
> ./venv/bin/pip install -U mloader gallery-dl
> ```
> 
> and then replace **main**.py and loader.py in all venv/lib??/python??/site-packages/mloader/ where ?? means go through all the possibilities, then you can user mloader in venv/bin which just wraps mloader in the venv

Followed every step meticulously, unfortunately still not working. __main__ is correctly recognized as edited (verified via log statements), while loader isn't

**Comment by benneti** [comment]
could you show me what the command is you run exactly? And maybe try to delete the __pycache__ folder just to be sure

**Comment by benneti** [comment]
@hurlenko if you have a few minutes you could review and merge this, such that the installation will be simpler.

**Comment by Nickelza** [comment]
> could you show me what the command is you run exactly? And maybe try to delete the __pycache__ folder just to be sure
> EDIT: maybe it will work by running venv/bin/activate and then try mloader again (at least thats how I use it) 

`mkdir venv 
python -m venv venv 
venv\Scripts\pip install -U pip 
venv\Scripts\pip install -U mloader gallery-dl`

I'll let you know once I run ```
activate
``` command

**Comment by Nickelza** [comment]
Correctly working after `activate` command, thanks a lot @benneti!

**Comment by benneti** [comment]
No problem, then I guess for some reason you initially used the version you first setup that was broken somehow...

**Comment by Nickelza** [comment]
Was able to figure out the error. Having installed mloader via pip (master release), when the module was imported in __main__ (`from mloader import loader`), it was the installed release that was being imported, and not the modified local file. I've now edited the installed file in Pyton38/lib/sites-packages/mloader and now it's working fine

**Comment by benneti** [comment]
seems to be implemented now

**Comment by hurlenko** [comment]
Hi @benneti!

Sorry for the late response, didn't have much time to work on the project 😅. So I followed your implementation but used a slightly different approach. Didn't want to bother you to make updates. Anyways it was really helpful, thanks! If you find any issues just let me know.

**Comment by benneti** [comment]
no problem, seems to work just fine!

**Pull request closed without merging**
