### PR TITLE
Handling API change

### LINKED ISSUE #61: Error when downloading a manga
I don't know if they have updated the web or what exactly it is because until yesterday the downloads were working without problems.

Here is what the mloader tells me when downloading

mloader

 - OS: Windows 10 x64
 - Python version: python 3.11.6 x64
 - mloader version: 1.1.11
 - Mangaplus URL: https://mangaplus.shueisha.co.jp/viewer/2010475

### PR DESCRIPTION
**Pull request by dousherve**
Hi,

As you might have noticed, the MANGA Plus API recently changed.

I took a look at the source code of the viewer and tried to update `response.proto` and `loader.py` accordingly **for the `title_detailV3` API call only**. Keep in mind that other parts of the API also changed, and I didn't thoroughly check whether or not the `proto` file is fully accurate (it's most likely not), since I couldn't find one in their sources (it's very likely that I just missed it).

I'm very sorry if I made obvious mistakes, or if I missed something else that needs attention. I couldn't sleep and wanted to fix this quickly. I didn't know anything about protobuf, since I could use raw JSON responses in my own code (they don't allow that anymore).

For now, this seems to fix hurlenko/mloader#61.

### CODE REVIEW

**Comment by CanonGear33** [comment]
Sorry i'm kinda new to coding and github, how to apply your modifications to the mloader on my PC ?

**Comment by Kanbei-Kikuchiyo** [comment]
Hi, it doesn't seem that the fix was integrated in the main branch, as I see the last changes are still from 3 months ago; when I reinstall mloader (`pip install mloader`), I still have version 1.1.11 and still same issue with downloading mangas.

**Comment by CanonGear33** [comment]
@10SecondsToWaste Thank ! i did it but it's still not working... something wrong here ?
image
image

**Comment by CanonGear33** [comment]
@10SecondsToWaste Did it, but still not working ^^" (thx for taking your time to help me btw 🫶 )
image

**Comment by CanonGear33** [comment]
@10SecondsToWaste I retried by installing directly with 
$ pip install git+https://github.com/hurlenko/mloader@refs/pull/62/head
and it worked ! I suppose that what you meaned haha, thnak you ! 🫶

**Comment by Kanbei-Kikuchiyo** [comment]
Thanks @10SecondsToWaste!

**Comment by aletga** [comment]
@10SecondsToWaste Thank !

**Comment by MariusMedo** [comment]
Ahm, sorry, but
`pip install --force-reinstall git+https://github.com/hurlenko/mloader@refs/pull/62/head`
does not work anymore... Did you remove the file?

As I am a beginner, let me explain what I did:
I just put the code into the command line and pressed "Enter".

This is, what happened:
Screenshot 2024-06-02 232118

How do I install "git"? I didn't do it before, when I first installed mloader. So why do I need it now? Sorry for my stupid questions, I am no developer :/

**Comment by dousherve** [comment]
Sorry I wasn't available to answer your questions. Thanks a lot @10SecondsToWaste

**Comment by cakgooder** [comment]
> @MariusMedo You can download Git from [here](https://git-scm.com/download/win). Long story short, `pip` needs Git to clone the repository; you can also manually download [the repository at this specific commit](https://github.com/dousherve/mloader/tree/dcf94330fc79c8d2fe156ab39d35ecf603ad3a9a) and install from disk, but that would be unnecessarily complicated.
> 
> Besides, there's no telling if this will ever happen again. With Git installed, you'll be ready when the next time comes.

Thank you for the help @10SecondsToWaste. It worked for me.

**Comment by DinaValentine** [comment]
The url of **@10SecondsToWaste** is no longer working, you can enter and encounter the 404 error

So the solution to install

pip install git + [https://github.com/hurlenko/mloader@refs/pull/62/head]()

It is not working anymore and you get this error. 

error

**Can someone help me solve this error, soon I will not be able to download certain mangas since Mangaplus only allows the last 3 mangas.** 

｡ﾟ･ (>﹏<) ･ﾟ｡  Pleaseee  (╯︵╰,)

**Comment by dousherve** [comment]
Hi,

You need to type the URL exactly as stated: `pip install --force-reinstall git+https://github.com/hurlenko/mloader@refs/pull/62/head`

Note the `+` between `git` and `https`.

**Comment by hurlenko** [comment]
@dousherve Thanks for the fix, released in mloader v1.1.12

**Comment by DinaValentine** [comment]
@hurlenko Thanks the update, all is working

**Comment by MariusMedo** [comment]
Works for me too now :) This git installation somehow didn't, but I am happy now, as it works perfectly fine after uninstalling 1.1.11 and reinstalling 1.1.12

**Pull request merged**
