### PR TITLE
Changing incorrect license label

### PR DESCRIPTION
**Pull request by NovusEdge**
Fixes: #30

### CODE REVIEW

**Comment by NovusEdge** [comment]
@hurlenko please review and merge if everything is ok

**Comment by hurlenko** [comment]
I'm afraid this is not the correct classifier. You can check the list here - https://pypi.org/classifiers/

The one that we need is `License :: OSI Approved :: GNU General Public License v3 (GPLv3)`

**Comment by NovusEdge** [comment]
I see, well I'll make the necessary changes

**Comment by hurlenko** [comment]
Thanks!

**Pull request merged**
